# Default values for my-app.
services:
  frontend:
    name: frontend
    replicaCount: 1
    image:
      repository: kyncore/multi-service-frontend
      tag: f3b8e4713504ca85e12cfbaa2dde752eeb6d04e4
      pullPolicy: IfNotPresent
    containerPort: 80
    servicePort: 80
  backend:
    name: backend
    replicaCount: 1
    image:
      repository: kyncore/multi-service-backend
      tag: f3b8e4713504ca85e12cfbaa2dde752eeb6d04e4
      pullPolicy: IfNotPresent
    containerPort: 3001
    servicePort: 3001
