# Default values for my-app.
services:
  frontend:
    name: frontend
    replicaCount: 1
    image:
      repository: kyncore/multi-service-frontend
      tag: 311ccad8e75f679378ebecbf91b7ad091ea4c88a
      pullPolicy: IfNotPresent
    containerPort: 80
    servicePort: 80
  backend:
    name: backend
    replicaCount: 1
    image:
      repository: kyncore/multi-service-backend
      tag: 311ccad8e75f679378ebecbf91b7ad091ea4c88a
      pullPolicy: IfNotPresent
    containerPort: 3001
    servicePort: 3001
